### ISSUE TITLE
Call to recipes?popular=true and recipes?featured=true returning wrong values

### ISSUE THREAD

**Issue by aeisses** [aeisses/FACCookBookServer#13]
The call to recipes?popular=true and recipes?featured=true are returning an array of recipes, they should be returning a list of recipes ids.

Is it possible to correct this?

**Comment by colinmacdonald** [comment]
The way it's implemented is to just filter from the full list of recipes. We could add query strings for what fields should be returned `field[n]=id`. No field query string would would return everything, 1 or more field query strings would only return the requested fields.

**Comment by aeisses** [comment]
Can I add that to the query field in the request? How?

**Comment by colinmacdonald** [comment]
Added query string `only_ids=true` to return an array of ids
