### ISSUE TITLE
Need a script to update a recipe not just import

### ISSUE THREAD

**Issue by aeisses** [aeisses/FACCookBookServer#14]
At the moment we have the import.js script. This works fine to add recipes to the database, but we need a script that will allow updates to the existing recipes in the database.

Date updated needs to be updated when a recipe is updated.

**Comment by aeisses** [comment]
I have been playing with the update it does not seem to be working properly for changing values of a recipe already in the system. I was able to update the featured flag, but not values of the recipe. I will continue to look at this.

**Comment by aeisses** [comment]
I just did some testing with the update script. It does not seem to be working at all.

**Comment by colinmacdonald** [comment]
Fixed the update script. Basically the script expected the server to handle batch requests but the server only handles updating a single record at a time.
