### ISSUE TITLE
Popular recipes should not return any if all are at zero

### ISSUE THREAD

**Issue by aeisses** [aeisses/FACCookBookServer#15]
Popular should return no recipes with a value of zero. At the moment it is returning all the values.

**Comment by colinmacdonald** [comment]
The way popular was implemented is it will return the most favorited recipes and limit the results to the config value `POPULAR_LIMIT`. If that `POPULAR_LIMIT` isn't set that may be why it's returning all recipes.

**Comment by aeisses** [comment]
If I set the POPULAR_LIMIT to 1, it will only return recipes that have at least one favourite?

**Comment by colinmacdonald** [comment]
No, it will return only 1 recipe (the most favorited recipe) when you search for popular recipes.

The query is simply sorting the recipes by the amount of times that it was favorited (DESC) then limiting the amount of results it gives you based off that `POPULAR_LIMIT` value.

**Comment by aeisses** [comment]
Can we eliminate recipes that have not be favourited from the initial query? Only apply the query to recipes that have been favourited at least once.

**Comment by colinmacdonald** [comment]
You are defining "popular" as one person favoriting it?

**Comment by aeisses** [comment]
No, I do not want anything returned if none of the recipes are favoured.

**Comment by colinmacdonald** [comment]
Made the popular list require at least 1 favourite to be included
