### ISSUE TITLE
Implement the REST API

### ISSUE THREAD

**Issue by aeisses** [aeisses/FACCookBookServer#6]
The server needs to have the rest API implemented. This will require all the REST calls to be added. See the design doc for details: https://docs.google.com/document/d/1oS3ep-lprY_o2f96LWxoC7fSPE112CpG7WYrby54xSY/edit#heading=h.c3v2g8tj5vzv

**Comment by jeffandersen** [comment]
I think the image server ends up being an endpoint here that just ships them to s3 or something.

But that brings up a good question. What are their resources for serving this app? @aeisses

Wouldn't want to over complicate this with aws and them not be in a position to support the resources required

**Comment by jeffandersen** [comment]
(Meaning #2 is tied to this)

**Comment by aeisses** [comment]
That is a good question. I am not really sure how to do that.

Can the images be served from any server? Ideally I would like to reduce cost. The EAC does have a local server we might be able to use to server images.

**Comment by jeffandersen** [comment]
Yeah you just run into issues with doing it with node.

It would make sense if we set them up with nginx to serve the images and
then hat would also route to the node server API.

**Comment by jeffandersen** [comment]
It might be best, like we said at lunch today, to do the server in node and then just get them set up on S3. S3 itself costs pennies until you're a high traffic system.

**Comment by aeisses** [comment]
If we setup the S3 account in my name is it easy to switch to someone else?
